services:
  nextcloud:
    image: nextcloud:28
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - tenant

volumes:
  nextcloud_data:
